blank_issues_enabled: true
contact_links:
  - name: Veinminer on CurseForge
    url: https://www.curseforge.com/minecraft/mc-mods/profets-veinminer
    about: Downloads, the full description and the changelog
